name: inboxmonkeys
favicon: null
layout_spectrum: 0.1732022361829877
typography_spectrum: 0.7841096092015505
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f8fa'
    - '#000000'
    - '#009eac'
    - '#9e7649'
    - '#126266'
  brandStrength: 0.875
  lightness: 0.9375
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
